language: cpp
sudo: required
dist: trusty
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
env:
  matrix:
  - LLVM_CONFIG=llvm-config-3.8 CLANG=clang-3.8
  - LLVM_CONFIG=llvm-config-3.5 CLANG=clang-3.5
  - LLVM_CONFIG=llvm-config-5.0 CLANG=clang-5.0
  - LLVM_CONFIG=llvm-config-6.0 CLANG=clang-6.0
  - LLVM_CONFIG=llvm-config-7.0 CLANG=clang-7.0

matrix:
  exclude:
    - os: osx
      compiler: gcc
    - os: osx
      env: LLVM_CONFIG=llvm-config-5.0 CLANG=clang-5.0
# blacklist some branches
branches:
  only:
    - develop
    - master
    - dev-llvm70
before_install:
  - |
    if [[ "$(uname)" = "Linux" ]]; then
      sudo apt-get update -qq
      sudo apt-get install wget p7zip-full p7zip-rar
      if [[ "$LLVM_CONFIG" = "llvm-config-7.0" ]]; then
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository -y "deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main"
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        for i in {1..5}; do sudo apt-get update -y && break || sleep 15; done
        sudo apt-get install -y llvm-7-dev clang-7 libclang-7-dev llvm-7-dev
      elif [[ "$LLVM_CONFIG" = "llvm-config-6.0" ]]; then
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository -y "deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main"
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        for i in {1..5}; do sudo apt-get update -y && break || sleep 15; done
        sudo apt-get install -y llvm-6.0-dev clang-6.0 libclang-6.0-dev llvm-6.0-dev
      elif [[ "$LLVM_CONFIG" = "llvm-config-5.0" ]]; then
        wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
        sudo apt-add-repository -y "deb https://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main"
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        for i in {1..5}; do sudo apt-get update -y && break || sleep 15; done
        sudo apt-get install -y llvm-5.0-dev clang-5.0 libclang-5.0-dev llvm-5.0-dev
      else
        sudo apt-get install -qq clang-3.5 libclang-3.5-dev llvm-3.8-dev clang-3.8 libclang-3.8-dev llvm-3.8-dev
      fi
    fi
  - |
    if [[ "$(uname)" = "Darwin" ]]; then
      if [[ "$LLVM_CONFIG" = "llvm-config-3.8" ]]; then
        curl -O http://releases.llvm.org/3.8.0/clang+llvm-3.8.0-x86_64-apple-darwin.tar.xz
        tar xf clang+llvm-3.8.0-x86_64-apple-darwin.tar.xz
        ln -s clang+llvm-3.8.0-x86_64-apple-darwin/bin/llvm-config llvm-config-3.8
        ln -s clang+llvm-3.8.0-x86_64-apple-darwin/bin/clang clang-3.8
      elif [[ "$LLVM_CONFIG" = "llvm-config-3.5" ]]; then
        curl -O http://releases.llvm.org/3.5.2/clang+llvm-3.5.2-x86_64-apple-darwin.tar.xz
        tar xf clang+llvm-3.5.2-x86_64-apple-darwin.tar.xz
        ln -s clang+llvm-3.5.2-x86_64-apple-darwin/bin/llvm-config llvm-config-3.5
        ln -s clang+llvm-3.5.2-x86_64-apple-darwin/bin/clang clang-3.5
      elif [[ "$LLVM_CONFIG" = "llvm-config-5.0" ]]; then
        curl -O http://releases.llvm.org/5.0.1/clang+llvm-5.0.1-x86_64-apple-darwin.tar.xz
        tar xf clang+llvm-5.0.1-x86_64-apple-darwin.tar.xz
        ln -s clang+llvm-5.0.1-final-x86_64-apple-darwin/bin/llvm-config llvm-config-5.0
        ln -s clang+llvm-5.0.1-final-x86_64-apple-darwin/bin/clang clang-5.0
      elif [[ "$LLVM_CONFIG" = "llvm-config-6.0" ]]; then
        curl -O http://releases.llvm.org/6.0.0/clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz
        tar xf clang+llvm-6.0.0-x86_64-apple-darwin.tar.xz
        ln -s clang+llvm-6.0.0-x86_64-apple-darwin/bin/llvm-config llvm-config-6.0
        ln -s clang+llvm-6.0.0-x86_64-apple-darwin/bin/clang clang-6.0
      elif [[ "$LLVM_CONFIG" = "llvm-config-7.0" ]]; then
        curl -O http://releases.llvm.org/7.0.0/clang+llvm-7.0.0-x86_64-apple-darwin.tar.xz
        tar xf clang+llvm-7.0.0-x86_64-apple-darwin.tar.xz
        ln -s clang+llvm-7.0.0-x86_64-apple-darwin/bin/llvm-config llvm-config-7.0
        ln -s clang+llvm-7.0.0-x86_64-apple-darwin/bin/clang clang-7.0
      fi
      
      curl -O https://raw.githubusercontent.com/develar/7zip-bin/master/mac/7za
      chmod +x ./7za
      mv ./7za ./7z
      export PATH=$PWD:$PATH
    fi
script:
  - |
    if [ "$(uname)" = "Linux" ] && [ "$LLVM_CONFIG" = "llvm-config-7.0" ]; then
      make LLVM_CONFIG=$(which llvm-config-7) CLANG=$(which clang-7) test
    else
      make LLVM_CONFIG=$(which $LLVM_CONFIG) CLANG=$(which $CLANG) test
    fi
